### ISSUE TITLE
Dear RTXT25,

### ISSUE THREAD

**Issue by chrystom** [RTXT25/crappy-cplatform-fighter#1]
IT'S REALLY ANNOYING ME HOW YOU HAVE A TOP-LEVEL SUBDIRECTORY AND IT WOULD SOOTHE MY MIND IF YOU COULD RECTIFY THIS. ALSO THE FACT, YOUR README FILE HAS A EXTENSION OF `.mb` INSTEAD OF `.md` IS KEEPING ME UP AT NIGHT.

IT WOULD BE VERY NICE IF YOU COULD FIX THESE TWO MISTAKES.

`-SINCERELY, CHRYSTOM (FLIDO)`

**Comment by RTXT25** [comment]
no
